### ISSUE TITLE
source and target datasets printed as only (3670,)

### ISSUE THREAD

**Issue by aswinr22** [akshath123/RGB_to_GRAYSCALE_Autoencoder-#1]
successfully resized the image and while running the first code snippet for preparing the dataset for training the autoencoder printed as only (3670,)

**Comment by akshathvarugeese** [comment]
Hi, aswin22 are you using the same dataset used in the tutorial or custom dataset? If custom dataset are the images for training or test have variable dimension, i.e. does each image have variable dimension in your training or testing set?

**Comment by aswinr22** [comment]
Dataset  same that in the tutorial
